### ISSUE TITLE
CI와 CD의 분리

### ISSUE THREAD

**Issue by likelasttime** [likelasttime/Auth-Service#32]
**Is your feature request related to a problem? Please describe.**
CI와 CD가 같이 있으니 push될 때마다 배포까지 같이 되는 문제가 있다.

**Describe the solution you'd like**
CI와 CD를 분리한다.
CI는 main, develop 브랜치에 pull_request를 했을 때 작동하게 한다.

**Additional context**
수정해야 할 코드 👇
```
name: Java CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          arguments: build
      - name: executing remote ssh commands using key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          scripts: |
            ./deploy.sh
```  

**References**
https://steady-coding.tistory.com/473
